---
# Source: discordsoundboard/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: discordsoundboard
  labels:
    helm.sh/chart: discordsoundboard-0.1.0
    app.kubernetes.io/name: discordsoundboard
    app.kubernetes.io/instance: discordsoundboard
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: discordsoundboard/templates/service-api.yaml
apiVersion: v1
kind: Service
metadata:
  name: discordsoundboard-api
  labels:
    helm.sh/chart: discordsoundboard-0.1.0
    app.kubernetes.io/name: discordsoundboard
    app.kubernetes.io/instance: discordsoundboard
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: discordsoundboard
    app.kubernetes.io/instance: discordsoundboard
---
# Source: discordsoundboard/templates/service-client.yaml
apiVersion: v1
kind: Service
metadata:
  name: discordsoundboard-client
  labels:
    helm.sh/chart: discordsoundboard-0.1.0
    app.kubernetes.io/name: discordsoundboard
    app.kubernetes.io/instance: discordsoundboard
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: discordsoundboard
    app.kubernetes.io/instance: discordsoundboard
---
# Source: discordsoundboard/templates/deployment-api.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discordsoundboard-api
  labels:
    helm.sh/chart: discordsoundboard-0.1.0
    app.kubernetes.io/name: discordsoundboard
    app.kubernetes.io/instance: discordsoundboard
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: discordsoundboard
      app.kubernetes.io/instance: discordsoundboard
  template:
    metadata:
      labels:
        app.kubernetes.io/name: discordsoundboard
        app.kubernetes.io/instance: discordsoundboard
    spec:
      serviceAccountName: discordsoundboard
      securityContext:
        {}
      containers:
        - name: discordsoundboard
          securityContext:
            {}
          image: "okteto.dev/client:1.16.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
---
# Source: discordsoundboard/templates/deployment-client.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discordsoundboard-client
  labels:
    helm.sh/chart: discordsoundboard-0.1.0
    app.kubernetes.io/name: discordsoundboard
    app.kubernetes.io/instance: discordsoundboard
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: discordsoundboard
      app.kubernetes.io/instance: discordsoundboard
  template:
    metadata:
      labels:
        app.kubernetes.io/name: discordsoundboard
        app.kubernetes.io/instance: discordsoundboard
    spec:
      serviceAccountName: discordsoundboard
      securityContext:
        {}
      containers:
        - name: discordsoundboard
          securityContext:
            {}
          image: "okteto.dev/api:1.16.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
---
# Source: discordsoundboard/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: discordsoundboard
  labels:
    helm.sh/chart: discordsoundboard-0.1.0
    app.kubernetes.io/name: discordsoundboard
    app.kubernetes.io/instance: discordsoundboard
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    dev.okteto.com/generate-host: "true"
spec:
  rules:
    - http:
        paths:
          - path: /api
            backend:
              serviceName: discordsoundboard-api
              servicePort: 80
          - path: /
            backend:
              serviceName: discordsoundboard-client
              servicePort: 80
---
# Source: discordsoundboard/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "discordsoundboard-test-connection"
  labels:
    helm.sh/chart: discordsoundboard-0.1.0
    app.kubernetes.io/name: discordsoundboard
    app.kubernetes.io/instance: discordsoundboard
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['discordsoundboard:80']
  restartPolicy: Never
