stages:
  - deploy

services:
  deploy:
    image: docker
    stage: deploy
    script:
        - mkdir $DOCKER_CERT_PATH
        - echo "$CA" > $DOCKER_CERT_PATH/ca.pem
        - echo "$CLIENT_CERT" > $DOCKER_CERT_PATH/cert.pem
        - echo "$CLIENT_KEY" > $DOCKER_CERT_PATH/key.pem
        - docker-compose build
        - docker-compose down
        - docker-compose up -d --force-recreate
        - rm -rf $DOCKER_CERT_PATH
      only:
        - master
      variables:
        DOCKER_TLS_VERIFY: "1"
        DOCKER_HOST: "tcp://[YOUR_INSTANCE_IP]:2376"
        DOCKER_CERT_PATH: "certs"
