version: '3'
services:

  api:
    image: discordsoundboard_api:latest
    volumes:
      - uploads-volume:/uploads
    environment:
      - CLIENT_ID
      - CLIENT_SECRET
      - BOT_TOKEN
      - NODE_ENV=production

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: 'dsb'
      POSTGRES_USER: 'dsb'
      POSTGRES_PASSWORD: $DB_PASSWORD


  nginx:
    build: nginx/
    ports:
      - '80:80'

  client:
    image: discordsoundboard_client:latest

volumes:
  uploads-volume:
