version: '3'
services:

  api:
    build: .
    volumes:
      - uploads-volume:/uploads
    environment:
      - CLIENT_ID
      - CLIENT_SECRET
      - BOT_TOKEN
      - NODE_ENV=production

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'

  front:
    build: client/

volumes:
  uploads-volume:
