version: '2'
services:

  api:
    build: .

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - app-volume:/var/www/
    ports:
      - '80:80'

  front:
    build: web-old/web-client/
    volumes:
      - app-volume:/var/www/

volumes:
    app-volume:
