version: '3'
services:

  api:
    image: ggresillion/discordsoundboard_api:latest
    volumes:
      - uploads-volume:/uploads
    environment:
      - NODE_ENV=production
      - CLIENT_ID
      - CLIENT_SECRET
      - BOT_TOKEN
      - DB_HOST=postgres
      - DB_PASSWORD
    depends_on:
      - postgres

  postgres:
    image: postgres:12-alpine
    volumes:
      - ./database-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'dsb'
      POSTGRES_USER: 'dsb'
      POSTGRES_PASSWORD: $DB_PASSWORD


  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on: 
      - api
      - client 

  client:
    image: ggresillion/discordsoundboard_client:latest

volumes:
  uploads-volume:
  database-volume:
