version: '3'
services:

  api:
    build: .
    volumes:
      - uploads-volume:/uploads
    environment:
      - CLIENT_ID
      - CLIENT_SECRET
      - BOT_TOKEN
      - NODE_ENV=production

  postgres:
    image: postgres:11
    environment:
      POSTGRES_DB: 'dsb'
      POSTGRES_USER: 'dsb'
      POSTGRES_PASSWORD: 'dsb'


  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'

  front:
    build: client/

volumes:
  uploads-volume:
