apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "discordsoundboard.fullname" . }}
  annotations:
    dev.okteto.com/generate-host: "true"
spec:
  rules:
    - http:
        paths:
          - path: /api
            backend:
              serviceName: api
              servicePort: http
          - path: /
            backend:
              serviceName: client
              servicePort: http