apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  clientId: {{ .Values.api.clientId | b64enc | quote }}
  clientSecret: {{ .Values.api.clientSecret | b64enc | quote }}
  botToken: {{ .Values.api.botToken | b64enc | quote }}