apiVersion: v1
kind: Service
metadata:
  name: {{ include "discordsoundboard.fullname" . }}-api
  labels:
    {{- include "discordsoundboard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "discordsoundboard.selectorLabels" . | nindent 4 }}
